### PR TITLE
Hdf5 cache

### PR DESCRIPTION
**Pull request by jreadey**
Added a cache pool to HDF5Dataset.  On getitem, 2D blocks (100x100) are read from disk.

### CODE REVIEW

**Comment by andrewcollette** [comment]
Closing since #36 is merged.

**Comment by jreadey** [comment]
Andrew, try out this file with master vs. this branch: https://s3.amazonaws.com/hdfgroup/data/hdf5test/hapmap_compressed.h5.
It doesn't seem usable using the chunk cache.

**Comment by andrewcollette** [comment]
That file is using a pathological chunk size of 25.5 MB, way larger than the 1 MB recommended by the HDF Group and just slightly larger than the 25 MB default per-dataset value on master.

A universal solution would be to inspect the dataset's metadata before opening, and set the cache on a per-dataset basis to at least 1 or 2 chunks, using H5Pset_chunk_cache:

https://hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-SetChunkCache

**Comment by andrewcollette** [comment]
Btw, a Python-side cache would be fine for our initial release if you're volunteering to shake out the bugs. :) We can polish it up later if problems crop up.  The main thing is to get a release going.  I'll leave the decision up to you.

Also, should we make a release milestone (0.9) to sort the bugs and see where we stand?

**Comment by jreadey** [comment]
Inspecting the dataset's metadata is a good idea, I'll try that out.

Release 0.9?  We're at 0.5.0, let's bump to 0.6.0.  We may need a few iterations to get to 1.0.

**Comment by andrewcollette** [comment]
Yes, 0.9 was a typo. :)  Mostly interested in what will be our first public release, and what has to happen to get there.

It occurred to me that even if we got HDF5's caching sorted out, things like OpenDAP may not like having data accessed point-by-point.  #39 adds a similar tile mechanism, plus eviction, at the GUI level.  Should work with anything implementing the Array interface.

I think we're closing in on it!

**Comment by jreadey** [comment]
I tried doing a repack on the hapmap file:
```
h5repack -l Hapmap:CHUNK=100 hapmap_compressed.h5 hapmap_repack.h5
```
When viewing with Compass, it's better but still a bit pokey.

I'll try with your #39.

**Comment by jreadey** [comment]
I'd like to get the public release out next week.   My todo items are: write up release notes, doc pages, project page, blog article.  Code wise I think we're good for a release - but do want to look into the plotting issues with large datasets.

**Comment by andrewcollette** [comment]
Just noticed this was still open; closing.

**Pull request closed without merging**
