### PR TITLE
Added Open Recent file menu

### PR DESCRIPTION
**Pull request by oyarzun**
use wx.FileHistory to open recently opened files from the file menu

### CODE REVIEW

**Comment by jreadey** [comment]
@oyarzun, Thanks for your contribution!  Can you send me your contact info to jreadey AT hdfgroup.org?  We'd like you to submit a contributor's agreement for any code to be merged to the HDFGroup organization.

**Comment by jreadey** [comment]
@oyarzun, it looks like the file history list will get longer and longer as more files are opened.  Could you add a "clear" menu item to cleanup the history?

So the "Open Recent" menu would look like this:

<file1>
<file2>
<file3>
-----------
Clear Recent

**Comment by ajelenak-thg** [comment]
How about the Recent `n` Files approach? Only `n` (`n > 0`) number of files most recently open are kept.

**Comment by oyarzun** [comment]
It only keeps a maximum of 8 in the history.

self.filehistory = wx.FileHistory(8)

http://docs.wxwidgets.org/trunk/classwx_file_history.html#a30e3a3a1f92fc253cc0fc69eb6f27fd8

**Comment by ajelenak-thg** [comment]
Oops. Failed to notice that line.

**Comment by jreadey** [comment]
Merged to develop branch.
I made one change in the interest of reducing 'magic numbers' in the code:

```
MAX_RECENT_FILES = 8
...
self.filehistory = wx.FileHistory(MAX_RECENT_FILES)
```

**Comment by jreadey** [comment]
Has anyone tried this on Windows?  I get an error on opening a file due to a no 'RemoveFileHistory' method on FileHistory.

**Comment by giumas** [comment]
@jreadey : there are at least a couple of issues.. 

One is that the `url` creation is different on Windows (additional `\`). 

Another issue is that `RemoveFileToHistory` method does not exist: `http://wxpython.org/Phoenix/docs/html/FileHistory.html#FileHistory.RemoveFileFromHistory`. So I don't believe that this is a Windows specific issue.

**Comment by jreadey** [comment]
I'm not sure what's up RemoveFileFromHistory.  It's there on my Mac environment: wx.version() == '3.0.0.0 osx-cocoa (classic)'.

@oyarzun  - any thoughts on this?  Can you patch the url setup and provide an alternative for RemoveFileFromHistory if that is not available on all platforms?

**Comment by giumas** [comment]
@jreadey The issue is that in the current code is misspelled.. `RemoveFileToHistory` in place of `RemoveFileFromHistory`. Look at my PR: https://github.com/HDFGroup/hdf-compass/pull/68

**Comment by jreadey** [comment]
Oh I see.  This path was somehow getting triggered in Windows but not the Mac.

**Comment by giumas** [comment]
@jreadey Why is this PR still open?

**Comment by jreadey** [comment]
Closing.

**Comment by hyoklee** [comment]
Why doesn't OPeNDAP URL appear in Open Recent menu? Does history work on local files only?

**Comment by giumas** [comment]
The follow-on questions might be:
- do we want to collect the urls?
- if yes, do we want them on the same history list or in a dedicated one?

**Comment by hyoklee** [comment]
My vote is 'yes' for both. See the attached Panoply screenshot. 
panoply_history

**Comment by jreadey** [comment]
I think it will be best/easiest to put recent files/resources in the same history menu.

Is the wx FileHistory adaptable for strings that are not proper files?

**Pull request closed without merging**
