### PR TITLE
Add is_plottable method for Array node and disabling for string

### PR DESCRIPTION
**Pull request by giumas**
This implement a fix to: https://github.com/HDFGroup/hdf-compass/issues/70:

* Add ``is_plottable`` method to ``Array`` nodes
* Use the new method for ``Array`` classes in ``opendap_model``, ``hdf5_model``, ``array_model``, ``bag_model``

### CODE REVIEW

**Comment by jreadey** [comment]
Can the plot button be disabled when a string type is selected?  As is the user may be left wondering why nothing happened when the button was pressed.  Alternatively, have a popup dialog that says the selected data can not be displayed.

**Comment by giumas** [comment]
@jreadey Actually, as-is the button is not displayed for string types. 

If you try to reopen `grid_1_2d.h5/HDFEOS INFORMATION` as HDF5 Dataset:

capture

This fix the bug that was crashing the application.. I am sure that my current solution can be enhanced.

**Comment by jreadey** [comment]
I was looking at a compound type example where one of the fields was a string type.  The button stays visible and enabled as I selected different fields (some numeric, some string) of the dataset.
I've added the file "compound.h5" to the hdf5 Download script if you want to try it out.

**Comment by giumas** [comment]
This PR added a mechanism to disable the plot (by default, the ``is_plottable`` is ``True`` for all derived ``Array`` node), and then started to use it with string (both unicode ``dt.kind == 'U'`` and ascii ``dt.kind == 'S'``).

The naive solution for compound type (``dt.names is not None``) would be to also disable the plot. However, I believe that some compound type should still be plottable ..

**Comment by jreadey** [comment]
With compound types is_plotable is function of field type and what field (if any) the user has selected.

A simple approach would be to iterate through all the fields of the compound type and set is_plottable to true if there is at least one numeric field.

In this case on_plot should plot all the numeric fields if no field is selected.

**Pull request merged**
